In [3]:
import random
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

tab_url = "Housing.csv"
tab = pd.read_csv(tab_url)

tab.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [4]:
y = tab['price']
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [5]:
a = np.ones((len(y), 1))
# print(len(a))
a

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [13]:
# tab1 = pd.concat((tab['area'], tab['bedrooms'], tab['bathrooms']), axis=1).to_numpy()
tab1 = tab['area']#.to_numpy()
tab1 = tab1.array.reshape(1, len(tab1))

In [14]:
X = np.concatenate((a, tab1.T), axis=1).astype(int)
X

array([[   1, 7420],
       [   1, 8960],
       [   1, 9960],
       ...,
       [   1, 3620],
       [   1, 2910],
       [   1, 3850]])

In [15]:
y = y.to_numpy()
print(len(y))

545


In [16]:
# напишіть функцію гіпотези лінійної регресії у векторному вигляді;
def linear_regression(w: np.array, X: np.array):
  return w @ X.T

In [17]:
# # створіть функцію для обчислення функції втрат у векторному вигляді;
# y = w0 + w1*x
# y = w*X
def cost(y: np.array, h: np.array):
  return np.mean((h - y)**2)/2

In [18]:
def step_descent(w: np.array, X: np.array, y: np.array, learning_rate: float=0.01):
  m = len(y)
  h = linear_regression(w, X)
  return w - learning_rate * 1/m * X.T @ (h-y)

In [19]:
def grad_descent(w: np.array, X: np.array, y: np.array, epsilon: float=0.00001, num_iters: int=1000):
    last_cost_f = 10000000
    for i in range(num_iters):
      h = linear_regression(w, X)
      w = step_descent(w, X, y)
      new_cost_f = cost(y, h)
      if i % (num_iters / 10) == 0:
        print(f"i = {i}")
        print(f"last_cost_f = {last_cost_f}")
        print(f"new_cost_f = {new_cost_f}\n")

      if abs(last_cost_f - new_cost_f) < epsilon:
        print(f"abs(last_cost_f - new_cost_f) < {epsilon}")
        break
      last_cost_f = new_cost_f

    print(f"new_cost_f = {new_cost_f}\n")
    return w


In [22]:

# w = np.array([random.uniform(-5, 5), random.uniform(-5, 5), random.uniform(-5, 5), random.uniform(-5, 5)])
w = np.array([random.uniform(-5, 5), random.uniform(-5, 5)])
w1 = w.copy()
w

array([ 0.08661858, -1.20053045])

In [23]:
linear_regression(w, X)


array([ -8907.84933099, -10756.66622619, -11957.19667761,  -9003.89176711,
        -8907.84933099,  -9003.89176711, -10300.46465464, -19448.5066945 ,
        -9724.21003796,  -6902.96347711, -15846.91534023,  -7203.09608997,
        -7863.38783825,  -4201.76996141,  -9364.05090253,  -7203.09608997,
        -7923.41436082, -10204.42221853,  -5522.35345797,  -7707.31887957,
        -5186.20493158,  -8589.70876136,  -9664.18351539,  -5474.33223992,
       -10564.58135396,  -7851.38253374,  -7203.09608997, -10654.62113781,
        -9544.13047025,  -6602.83086426,  -8973.87850582,  -8403.62654139,
        -5858.50198437,  -7155.07487191,  -8211.54166917,  -8403.62654139,
        -8982.28221898, -10804.68744424,  -7203.09608997,  -7203.09608997,
        -7863.38783825,  -7635.28705248,  -7779.35070665,  -7203.09608997,
        -7203.09608997,  -7203.09608997,  -7203.09608997,  -7923.41436082,
        -5162.19432255,  -8931.85994002,  -8931.85994002,  -7593.26848668,
        -7203.09608997,  

In [58]:
# linear_regression(w, X)
w1 = step_descent(w1, X, y)
w1

array([2.88196889e+191, 1.74740568e+195])

In [59]:
w1 = grad_descent(w, X, y, num_iters=2000)
w1
# print(regressor.predict(np.array([[5, 1]])))

i = 0
last_cost_f = 10000000
new_cost_f = 13139020135231.717

i = 200
last_cost_f = nan
new_cost_f = nan

i = 400
last_cost_f = nan
new_cost_f = nan

i = 600
last_cost_f = nan
new_cost_f = nan

i = 800
last_cost_f = nan
new_cost_f = nan

i = 1000
last_cost_f = nan
new_cost_f = nan

i = 1200
last_cost_f = nan
new_cost_f = nan

i = 1400
last_cost_f = nan
new_cost_f = nan

i = 1600
last_cost_f = nan
new_cost_f = nan

i = 1800
last_cost_f = nan
new_cost_f = nan

new_cost_f = nan



<ipython-input-17-8ea696bab1b4>:5: RuntimeWarning: overflow encountered in square
  return np.mean((h - y)**2)/2
<ipython-input-19-61e7e6f041c4>:12: RuntimeWarning: invalid value encountered in double_scalars
  if abs(last_cost_f - new_cost_f) < epsilon:
<ipython-input-16-8b41b09b1784>:3: RuntimeWarning: overflow encountered in matmul
  return w @ X.T
<ipython-input-18-5405ae0c9f1e>:4: RuntimeWarning: invalid value encountered in subtract
  return w - learning_rate * 1/m * X.T @ (h-y)


array([nan, nan])

In [60]:
class LinearRegression:
  def __init__(self, lr: float=0.001, thr: float=0.00001, n_epochs: int=100):
    self.lr = lr
    self.thr = thr
    self.n_epochs = n_epochs
    self.w = np.array([random.uniform(-5, 5), random.uniform(-5, 5)])

  def predict(self, X: list):
    return self.w@X.T

  def update_weights(self, X: np.array, y: np.array):
    m = len(y)
    h = self.predict(X)
    self.w = self.w - self.lr * 1/m * X.T @ (h-y)

  def fit(self, X: np.array, y: np.array, w: np.array=None):
    if w is not None:
      self.w = w.copy()
    last_cost_f = 10000000
    for i in range(self.n_epochs):
      self.update_weights(X, y)
      new_cost_f = cost(y, self.predict(X))
      if i % (self.n_epochs / 10) == 0:
        print(f"i = {i}")
        print(f"last_cost_f = {last_cost_f}")
        print(f"new_cost_f = {new_cost_f}\n")

      if abs(last_cost_f - new_cost_f) < self.thr:
        break
      last_cost_f = new_cost_f

    print(f"new_cost_f = {new_cost_f}\n")
    return self.w


In [61]:
new_regressor = LinearRegression(n_epochs=2000)
new_regressor.fit(X, y, w)

i = 0
last_cost_f = 10000000
new_cost_f = 1.1181114680209324e+22

i = 200
last_cost_f = nan
new_cost_f = nan

i = 400
last_cost_f = nan
new_cost_f = nan

i = 600
last_cost_f = nan
new_cost_f = nan

i = 800
last_cost_f = nan
new_cost_f = nan

i = 1000
last_cost_f = nan
new_cost_f = nan

i = 1200
last_cost_f = nan
new_cost_f = nan

i = 1400
last_cost_f = nan
new_cost_f = nan

i = 1600
last_cost_f = nan
new_cost_f = nan

i = 1800
last_cost_f = nan
new_cost_f = nan

new_cost_f = nan



<ipython-input-17-8ea696bab1b4>:5: RuntimeWarning: overflow encountered in square
  return np.mean((h - y)**2)/2
<ipython-input-60-fa544b5ca0d7>:28: RuntimeWarning: invalid value encountered in double_scalars
  if abs(last_cost_f - new_cost_f) < self.thr:
<ipython-input-60-fa544b5ca0d7>:9: RuntimeWarning: overflow encountered in matmul
  return self.w@X.T
<ipython-input-60-fa544b5ca0d7>:14: RuntimeWarning: invalid value encountered in subtract
  self.w = self.w - self.lr * 1/m * X.T @ (h-y)


array([nan, nan])