In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import random
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [82]:
tab_url = "/content/drive/My Drive/Colab Notebooks/Housing.csv"
tab = pd.read_csv(tab_url)

tab.head(10)

price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000   7420         4          2        3      yes        no       no   
1  12250000   8960         4          4        4      yes        no       no   
2  12250000   9960         3          2        2      yes        no      yes   
3  12215000   7500         4          2        2      yes        no      yes   
4  11410000   7420         4          1        2      yes       yes      yes   
5  10850000   7500         3          3        1      yes        no      yes   
6  10150000   8580         4          3        4      yes        no       no   
7  10150000  16200         5          3        2      yes        no       no   
8   9870000   8100         4          1        2      yes       yes      yes   
9   9800000   5750         3          2        4      yes       yes       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished  
5              no             yes        2      yes   semi-furnished  
6              no             yes        2      yes   semi-furnished  
7              no              no        0       no      unfurnished  
8              no             yes        2      yes        furnished  
9              no             yes        1      yes      unfurnished

In [86]:
# напишіть функцію гіпотези лінійної регресії у векторному вигляді;
def linear_regression(w: np.array, X: np.array):
  return w[0] + w[1] * X

w = np.array([3, 2])
x = np.array([5, 3])
result = linear_regression(w, x)
print(f"linear_regression: {result}")

linear_regression: [13  9]


In [94]:
# # створіть функцію для обчислення функції втрат у векторному вигляді;
def cost(w: np.array, X: np.array, y: np.array):
    m = len(X) * 2
    predict = linear_regression(w, X)
    res = np.mean((predict - y)**2)/2
    return res

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([2, 3, 4, 4, 5, 6, 6])
w = np.array([0.0, 0.0])

loss = cost(w, x, y)
print(f"Функція втрат cost: {loss}")

Функція втрат cost: 10.142857142857142


In [138]:
def step_descent(w: np.array, X: np.array, y: np.array, learning_rate: float=0.01):
    m = len(X)

    grad_w0 = (1/m) * np.sum(linear_regression(w, X) - y)
    grad_w1 = (1/m) * np.sum((linear_regression(w, X) - y) * X)

    w[0] -= learning_rate * grad_w0
    w[1] -= learning_rate * grad_w1

    return w


x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([2, 3, 4, 4, 5, 6, 6])
w = np.array([0.0, 0.0])

w = step_descent(w, x, y)
print(f"Оновлені ваги: {w}")

Оновлені ваги: [0.04285714 0.19857143]


In [139]:
# знайдіть найкращі параметри для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;
X = tab[['area', 'bedrooms', 'bathrooms']]
y = tab['price']

regres = LinearRegression()
regres.fit(X, y)

w = regres.coef_
w

array([3.78762754e+02, 4.06820034e+05, 1.38604950e+06])

In [123]:
# знайдіть ці ж параметри за допомогою аналітичного рішення;
def analit(X: np.array, y: np.array):
  # w = (X.T @ X)^(-1) @ X.T @ y
  w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
  return w

In [135]:
tab1 = tab[['area', 'bedrooms', 'bathrooms']]
y = tab['price']
a = np.ones((len(y), 1))
X2 = np.concatenate((a, tab1), axis=1).astype(int)
X2

array([[   1, 7420,    4,    2],
       [   1, 8960,    4,    4],
       [   1, 9960,    3,    2],
       ...,
       [   1, 3620,    2,    1],
       [   1, 2910,    3,    1],
       [   1, 3850,    3,    1]])

In [136]:
w2 = analit(X2, y)
w2 = w2[1:]
w2

array([3.78762754e+02, 4.06820034e+05, 1.38604950e+06])

In [140]:
# Порівняйте отримані результати.
print(w)
print(w2)

[3.78762754e+02 4.06820034e+05 1.38604950e+06]
[3.78762754e+02 4.06820034e+05 1.38604950e+06]
