In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
vector1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(vector1)


[0 1 2 3 4 5 6 7 8 9]


In [3]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matrix2 = np.zeros((3, 3))
print(matrix2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
matrix3 = np.random.randint(1, 10, (5, 5))
print(matrix3)

[[8 5 2 2 3]
 [4 6 8 8 8]
 [7 5 1 8 9]
 [4 8 2 9 9]
 [6 6 9 1 7]]


In [11]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix4 = np.random.rand(4, 4)
print(matrix4)

[[0.98300125 0.35123566 0.21790276 0.89290022]
 [0.38749215 0.53632957 0.17427323 0.7689896 ]
 [0.05398122 0.66393423 0.52223923 0.7024102 ]
 [0.5541538  0.22816647 0.02079655 0.21203559]]


In [14]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
#    та виконайте на них поелементні операції додавання, віднімання та множення.
vector5 = np.random.randint(1, 10, (5,))
vector5_2 = np.random.randint(1, 10, (5,))
print(vector5)
print(vector5_2)
print('\n')
print(vector5 + vector5_2)
print(vector5 - vector5_2)
print(vector5 * vector5_2)


[6 8 8 2 4]
[3 8 8 2 3]


[ 9 16 16  4  7]
[3 0 0 0 1]
[18 64 64  4 12]


In [15]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
vector6 = np.random.randint(1, 10, (7,))
vector6_2 = np.random.randint(1, 10, (7,))
print(vector6)
print(vector6_2)
print('\n')
print(np.dot(vector5, vector5_2))


[4 9 9 2 7 9 6]
[6 5 1 7 1 9 1]


162


In [17]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matrix7 = np.random.randint(1, 10, (2, 2))
matrix7_2 = np.random.randint(1, 10, (2, 3))
print(matrix7)
print('\n')
print(matrix7_2)
print('\n')
print(np.dot(matrix7, matrix7_2))


[[7 4]
 [5 6]]


[[6 1 7]
 [6 7 6]]


[[66 35 73]
 [66 47 71]]


In [19]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix8 = np.random.randint(1, 10, (3, 3))
matrix8_inv = np.linalg.inv(matrix8)
matrix8_dot = np.dot(matrix8, matrix8_inv)
print(matrix8)
print('\n')
print(matrix8_inv)
print('\n')
print(np.round(matrix8_dot, 8))

[[2 9 7]
 [1 3 1]
 [6 5 2]]


[[-0.01886792 -0.32075472  0.22641509]
 [-0.0754717   0.71698113 -0.09433962]
 [ 0.24528302 -0.83018868  0.05660377]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix9 = np.random.rand(4, 4)
matrix9_tr = matrix9.T
print(matrix9)
print('\n')
print(matrix9_tr)


[[0.55321187 0.34147884 0.99351122 0.45646374]
 [0.43928382 0.24552729 0.13374204 0.28873932]
 [0.84907433 0.71005369 0.61819285 0.37976434]
 [0.6583882  0.37909467 0.7593226  0.91686958]]


[[0.55321187 0.43928382 0.84907433 0.6583882 ]
 [0.34147884 0.24552729 0.71005369 0.37909467]
 [0.99351122 0.13374204 0.61819285 0.7593226 ]
 [0.45646374 0.28873932 0.37976434 0.91686958]]


In [28]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix10 = np.random.randint(1, 10, (3, 4))
vector10 = np.random.randint(1, 10, (4,))
vector10_2 = np.random.randint(1, 10, (4, 1))
print(matrix10)
print('\n')
print(vector10)
print('\n')
print(np.dot(matrix10, vector10))
print('\n')
print(vector10_2)
print('\n')
print(np.dot(matrix10, vector10_2))


[[4 1 6 4]
 [2 5 8 4]
 [3 6 7 8]]


[8 6 8 9]


[122 146 188]


[[2]
 [6]
 [4]
 [9]]


[[ 74]
 [102]
 [142]]


In [30]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matrix11 = np.random.rand(2, 3)
vector11 = np.random.rand(3,)
print(matrix11)
print('\n')
print(vector11)
print('\n')
print(np.dot(matrix11, vector11))


[[0.88108345 0.08136561 0.44808706]
 [0.7223235  0.72386971 0.0770021 ]]


[0.16484696 0.51807105 0.41191133]


[0.37196923 0.52580682]


In [31]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix12 = np.random.randint(1, 10, (2, 2))
matrix12_2 = np.random.randint(1, 10, (2, 2))
print(matrix12)
print('\n')
print(matrix12_2)
print('\n')
print(np.dot(matrix12, matrix12_2))


[[1 2]
 [2 2]]


[[4 6]
 [8 7]]


[[20 20]
 [24 26]]


In [32]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix13 = np.random.randint(1, 10, (2, 2))
matrix13_2 = np.random.randint(1, 10, (2, 2))
print(matrix13)
print('\n')
print(matrix13_2)
print('\n')
print(matrix13 * matrix13_2)


[[2 6]
 [6 3]]


[[1 6]
 [5 4]]


[[ 2 36]
 [30 12]]


In [33]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix14 = np.random.randint(1, 100, (5, 5))
print(matrix14)
print('\n')
print(matrix14.sum())



[[ 3  1 85 42 23]
 [28  6 94 45 55]
 [69 36 85 73 46]
 [37 32 26 33 73]
 [46 26 72 88 17]]


1141


In [34]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix15 = np.random.randint(1, 10, (4, 4))
matrix15_2 = np.random.randint(1, 10, (4, 4))
print(matrix15)
print('\n')
print(matrix15_2)
print('\n')
print(matrix15 - matrix15_2)


[[6 6 2 1]
 [4 1 2 7]
 [3 6 5 1]
 [2 8 5 4]]


[[6 7 5 7]
 [9 5 4 1]
 [2 7 9 7]
 [6 2 1 3]]


[[ 0 -1 -3 -6]
 [-5 -4 -2  6]
 [ 1 -1 -4 -6]
 [-4  6  4  1]]


In [37]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1
#     та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix16 = np.random.rand(3, 3)
vector16 = matrix16.sum(axis=1)
print(matrix16)
print('\n')
print(vector16)


[[0.51272977 0.96986428 0.27015114]
 [0.52446826 0.59643453 0.48694419]
 [0.40202376 0.46401995 0.03976571]]


[1.75274519 1.60784698 0.90580942]


In [38]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix17 = np.random.randint(1, 10, (3, 4))
print(matrix17)
print('\n')
print(matrix17 ** 2)



[[1 2 6 2]
 [1 1 9 6]
 [8 4 2 8]]


[[ 1  4 36  4]
 [ 1  1 81 36]
 [64 16  4 64]]


In [39]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50
#     та знайдіть вектор з квадратними коренями цих чисел.
vector18 = np.random.randint(1, 50, (4,))
print(vector18)
print('\n')
print(vector18 ** 0.5)


[ 3 22 24 15]


[1.73205081 4.69041576 4.89897949 3.87298335]
